# Generated by Django 6.0 on 2026-01-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_brand_productimage_alter_product_options_and_more'),
        ('virtual_tryon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectacleFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(help_text='Upload .glb or .gltf file', upload_to='frames_3d/')),
                ('scaling_factor', models.FloatField(default=1.0, help_text='Scale adjustment for the model')),
                ('offset_x', models.FloatField(default=0.0)),
                ('offset_y', models.FloatField(default=0.0)),
                ('offset_z', models.FloatField(default=0.0)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_model', to='catalog.productvariant')),
            ],
        ),
    ]
