# Generated by Django 6.0 on 2025-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_login_no_password',
            field=models.BooleanField(default=False, help_text='Allow login without password (username/email only)'),
        ),
    ]
