# Generated by Django 6.0 on 2025-12-23 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'My Primary Glasses'", max_length=100)),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('od_sphere', models.DecimalField(decimal_places=2, help_text='Sphere (SPH)', max_digits=4)),
                ('od_cylinder', models.DecimalField(blank=True, decimal_places=2, help_text='Cylinder (CYL)', max_digits=4, null=True)),
                ('od_axis', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('od_add', models.DecimalField(blank=True, decimal_places=2, help_text='Addition (ADD)', max_digits=4, null=True)),
                ('os_sphere', models.DecimalField(decimal_places=2, help_text='Sphere (SPH)', max_digits=4)),
                ('os_cylinder', models.DecimalField(blank=True, decimal_places=2, help_text='Cylinder (CYL)', max_digits=4, null=True)),
                ('os_axis', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('os_add', models.DecimalField(blank=True, decimal_places=2, help_text='Addition (ADD)', max_digits=4, null=True)),
                ('pd_single', models.DecimalField(blank=True, decimal_places=1, help_text='Single PD (e.g. 62.0)', max_digits=4, null=True)),
                ('pd_right', models.DecimalField(blank=True, decimal_places=1, help_text='Right PD (Mono)', max_digits=4, null=True)),
                ('pd_left', models.DecimalField(blank=True, decimal_places=1, help_text='Left PD (Mono)', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
